version: '3'

services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/user/src/app/
    command: sh -c 'cd frontend && npm start'
    ports:
      - '3000:3000'
    tty: true
